whynotmake-it/figmage

- lib/src/generators/color_theme_extension_generator.dart
- lib/src/generators/number_theme_extension_generator.dart
- lib/src/generators/text_style_theme_extension_generator.dart
- lib/src/generators/theme_extension_generator.dart
- test/src/generators/color_theme_extension_generator_test.dart
- test/src/generators/number_theme_extension_generator.dart
- test/src/generators/text_style_theme_generator_test.dart
> feat: added number generator, added BuildContext extension to ThemeExtensionGenerator

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/main.yaml
Updated dart coverage assistant version and PR template
> ci: updated dart coverage assistant

- .github/dependabot.yaml
Updated Dependabot to use a better PR message
> ci: update dependabot settings

- lib/src/data/generators/padding_generator.dart
- test/src/data/generators/padding_generator_test.dart
> feat: paddings generator

- .github/workflows/main.yaml
- lib/src/domain/models/config/config.g.dart
- lib/src/domain/models/tokens_by_file_type/tokens_by_type.freezed.dart
- lib/src/domain/models/typography/typography.freezed.dart
- lib/src/domain/models/variable/alias_or/alias_or.freezed.dart
- lib/src/version.dart
> fix: update coverage generation

- lib/src/data/generators/file_generators/base_file_generator.dart
- lib/src/data/generators/theme_extension_generators/mode_theme_extension_generator.dart
- lib/src/data/repositories/figma_variables_repository.dart
- lib/src/domain/models/config/config.dart
- lib/src/domain/models/config/config.g.dart
- lib/src/domain/models/design_token.dart
- lib/src/domain/models/style/design_style.dart
- lib/src/domain/models/tokens_by_file_type/tokens_by_type.dart
- lib/src/domain/models/variable/alias_or/alias_or.dart
- lib/src/domain/models/variable/alias_or/alias_or.freezed.dart
- lib/src/domain/models/variable/variable.dart
- lib/src/domain/providers/design_token_providers.dart
- lib/src/domain/providers/generator_providers.dart
- lib/src/domain/util/token_filter_x.dart
- test/src/domain/models/config/config_test.dart
- test/src/domain/providers/design_token_providers_test.dart
- test/src/domain/util/token_filter_x_test.dart
- test/test_util/mock/mock_variables.dart
> feat: handle unresolved values

- lib/src/data/generators/file_generators/padding_file_generator.dart
- lib/src/data/generators/file_generators/spacer_file_generator.dart
- lib/src/data/generators/reference_generators/padding_generator.dart
- lib/src/data/generators/reference_generators/reference_theme_class_generator.dart
- lib/src/data/generators/reference_generators/spacer_generator.dart
- lib/src/data/generators/theme_extension_generators/mode_theme_extension_generator.dart
- lib/src/data/repositories/figma_styles_repository.dart
- lib/src/data/util/converters/string_dart_conversion_x.dart
- lib/src/domain/models/style/design_style.dart
- lib/src/domain/util/token_filter_x.dart
- lib/src/domain/util/values_by_name_by_mode_x.dart
- pubspec.yaml
- test/src/data/generators/file_generators/color_file_generator_test.dart
- test/src/data/generators/generator_util_test.dart
- test/src/data/generators/reference_generators/padding_generator_test.dart
- test/src/data/generators/reference_generators/spacer_generator_test.dart
- test/src/data/generators/theme_extension_generators/color_theme_extension_generator_test.dart
- test/src/data/generators/theme_extension_generators/number_theme_extension_generator_test.dart
- test/src/data/generators/theme_extension_generators/text_style_theme_extension_generator_test.dart
- test/src/domain/models/style/color_style_test.dart
- test/src/domain/util/token_filter_x_test.dart
- test/test_util/mock/mock_styles.dart
- test/test_util/mock/mock_variables.dart
> feat: nullable field types if unresolved

- README.md
- lib/src/domain/models/config/config.dart
- lib/src/domain/models/config/config.g.dart
- test/src/domain/models/config/config_test.dart
- test/src/domain/providers/design_token_providers_test.dart
> docs: usage readme

- README.md
- lib/src/commands/forge/forge_command.dart
Updated README and documentation
> docs: finalize documentation

- README.md
> docs: fix README note

- README.md
> docs: fix info box again

- lib/src/domain/providers/design_token_providers.dart
> feat: silient for happy case

- .github/workflows/main.yaml
- .github/workflows/release.yaml
- CHANGELOG.md
- LICENSE
- lib/src/version.dart
- packages/figma_variables_api/CHANGELOG.md
- packages/figma_variables_api/LICENSE
- packages/figma_variables_api/pubspec.yaml
- packages/figmage_package_generator/CHANGELOG.md
- packages/figmage_package_generator/LICENSE
- packages/figmage_package_generator/pubspec.yaml
- pubspec.yaml
> chore: release prep

- melos.yaml
> ci: add generate in version hook

- .github/workflows/release.yaml
Adds tags to releases generated by melos action
> ci: included tags in git release workflow

- .github/workflows/version.yaml
> ci: updated version workflow to use tags without melos action

- .github/workflows/version.yaml
> ci: melos run version is not a thing

- .github/workflows/version.yaml
> ci: set git credentials in version action

- .github/workflows/main.yaml
- .github/workflows/version.yaml
> ci: removed publish dry run from version workflow

- CHANGELOG.md
- lib/src/version.dart
- packages/figma_variables_api/CHANGELOG.md
- packages/figma_variables_api/pubspec.yaml
- pubspec.yaml
- figma_variables_api@0.1.0-dev.4
- figmage@0.1.0-dev.4
> chore(release): publish packages

- .github/workflows/integration_tests.yaml
> ci: fix integration test secret

- .github/workflows/integration_tests.yaml
> ci: run integration tests with the changes from the PR

- lib/src/data/repositories/dart_post_generation_repository.dart
- lib/src/domain/repositories/variables_repository.dart
Fixed typos in unauthorised variables exception as well as a few info logs
> fix: typos in several log messages

- .github/workflows/main.yaml
- .github/workflows/tag_release.yaml
- .github/workflows/version.yaml
> ci: remove useless publishable check and fix version workflow

- .github/workflows/version.yaml
> ci: enable fetching tags in version workflow

- .github/workflows/integration_tests.yaml
- integration_test/full_integration_test.dart
- integration_test/generation_notifier_integration_test.dart
- integration_test/util/util.dart
- tool/readme_code_generator.dart
> test: fix integration test workflow to use Flutter SDK
